### ISSUE TITLE
Unable to use allOf/anyOf/oneOf

### ISSUE THREAD

**Issue by cyberwombat** [fastify/fluent-json-schema#102]
## 🐛 Bug Report

If I use `allOf/anyOf/oneOf` as part of `S.object()` the final output drops `"type": "object"` from the schema resulting in errors such as: `strict mode: missing type "object" for keyword "maxProperties" at "#/properties/definition" (strictTypes)`

## To Reproduce

```js
S.object().prop(
  'definition',
  S.object()
    .maxProperties(100)
    .allOf([
      S.ifThen(
        S.object().prop('type', S.const('foo')),
        S.object()
          .prop('parameters', S.object().prop('bar', S.string()))
          .required()
      )
    ])
)
```

## Expected behavior

```json
{
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "definition": {
         "type": "object",   /// THIS IS MISSING FROM OUTPUT
          "maxProperties": 100,
          "allOf": [
            {
              "if": {
                "properties": {
                  "type": {
                    "const": "foo"
                  }
                }
              },
              "then": {
                "properties": {
                  "parameters": {
                    "type": "object",
                    "properties": {
                      "bar": {
                        "type": "string"
                      }
                    }
                  }
                },
                "required": [
                  "parameters"
                ]
              }
            }
          ]
        }
      }
    }
```

## Your Environment

- *node version*: 14
- *fluent-json-schema version*: >=2.0.2
- *os*: Mac

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by cyberwombat** [comment]
My bad. I didn't place the `allOf` statement correctly.

**Comment by giovanni-bertoncelli** [comment]
@cyberwombat can you please share your final solution?

**Comment by cyberwombat** [comment]
@giovanni-bertoncelli it's been a minute since I did this but looking at this and my code I think the issue was that the `allof` needed to be at the root of the prop definition. I think something like this:
```
S.object().prop(
  'definition',
 $.allOf([
    S.object()...  
    ])
)
```

On my first example you can see that I am defining the prop as an  object then using the `allOf` for additional definitions but I believe it has to be the first thing and then in each `allOf` options you would add the `$.object()...` options.

Hopefully this helps.
