### ISSUE TITLE
additionalProperties() unexpected behaviour depending on definition order

### ISSUE THREAD

**Issue by ghost** [fastify/fluent-json-schema#106]
## 🐛 Bug Report
`additionalProperties()` changes behaviour depending on where it is positioned in the schema definition.
For example putting `additionalProperties()`after a `prop()` statement causes the prop to get the `additionalProperties` configuration instead of the root object. 

## To Reproduce

```js
const S = require('.')
console.log(
  S.object()
  .prop('test', S.string())
  .additionalProperties(false)
  .valueOf()
)
```

Results in:

```js
{
  '$schema': 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  properties: { test: { additionalProperties: false, type: 'string' } }
}
```

While this:

```js
const S = require('.')
console.log(
  S.object()
  .additionalProperties(false)
  .prop('test', S.string())
  .valueOf()
)
```

Results in:

```js
{
  '$schema': 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  additionalProperties: false,
  properties: { test: { type: 'string' } }
}
```

And that's the expected behaviour.

## Expected behavior

There should be no differences between the two different scenarios described above, and the second one has the expected result.

## Your Environment

- *node version*: 14.15.1
- *fastify version*: 3.9.2
- *os*: Mac
- *any other relevant information*: you're doing an amazing job!

## Related issues/questions

https://github.com/fastify/help/issues/368

**Comment by aboutlo** [comment]
This is expected. Any element declared after a `prop` is assigned to it, not to the root. 
So the correct syntax is:
```
S.object()
  .additionalProperties(false)
  .prop('test', S.string())
  .valueOf()
```

the idea was that you

**Comment by tasdflkjweio** [comment]
@aboutlo @mcollina hi both, can you please clarify this? I understand what you're saying and why. Is this pattern consistently applied though? For example...

```
S.object()
  .additionalProperties(false) // applies to root
  .prop('test', S.string()) // anything immediately after this acts on the property rather than root obj
  .required(['test']); // but does this belong here or does it need to moved higher up?
```

Thanks!

**Comment by Eomm** [comment]
Here is the code:

```js
const S = require('fluent-json-schema')

const x = S.object()
  .additionalProperties(false)
  .required(['asd']) // this is attached to the root obj
  .prop('test', S.string()).required() // this is referred to the prop obj and attached to the root obj

console.log(JSON.stringify(x.valueOf(), null, 2))

// {
//   "$schema": "http://json-schema.org/draft-07/schema#",
//   "type": "object",
//   "additionalProperties": false,
//   "properties": {
//     "test": {
//       "type": "string"
//     }
//   },
//   "required": [
//     "asd",
//     "test"
//   ]
// }
```
