### ISSUE TITLE
Duplicate `required()` generates invalid schema

### ISSUE THREAD

**Issue by boyander** [fastify/fluent-json-schema#114]
## 🐛 Bug Report

Calling `required()` twice on same prop duplicates key in `required` schema array `required:[<prop>,<prop>]` generating an invalid schema.

## To Reproduce

```js
const S = require('fluent-json-schema')

const schema = S.object()
  .prop('email', S.string()).required().required()
  
console.log(JSON.stringify(schema.valueOf(), undefined, 2))
```

causes invalid schema with duplicate `prop` in `required` array
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "email": {
      "type": "string"
    }
  },
  "required": [
    "email",
    "email"
  ]
}
```

https://replit.com/@boyander/duplicatedrequiredprop

## Expected behavior

Either throw an error if using `require()` twice or generate the `required:[]` array using a [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set)

## Your Environment

- *node version*: 12
- *os*: Mac

Also, congrats for this awesome package. We use it a lot at @core-school

**Comment by mcollina** [comment]
We are glad you like it!

Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by boyander** [comment]
Sure! Will work on it this weekend ☀️
