### ISSUE TITLE
There is no tags function

### ISSUE THREAD

**Issue by MomenNano** [fastify/fluent-json-schema#119]
There is no tags function `S.tags()`

I don't know if it's added in the latest draft or it can be added in the current draft (7)
## Motivation
I want to integrate it with fastify-swagger so I can make sections using those tags

## Example
```js
const userSchema = {
  body: S.tags('user')
     .object()
}
```

**Comment by aboutlo** [comment]
perhaps you can use `S.raw({tags:  ["user"], })`  https://github.com/fastify/fluent-json-schema/blob/master/docs/API.md#raw

**Comment by MomenNano** [comment]
Thanks for the fast reply.

It turns out that it just needed to be declared outside the body and response, like 

```js
const user= {
  description: 'login user',
  tags: ['user'],
  body: S.object()
    .prop('username', S.string().required())
    .prop('password', S.string().required()),
  response: {
    200: S.object()
  }
}
```
