### ISSUE TITLE
All props should be required by default

### ISSUE THREAD

**Issue by erfanium** [fastify/fluent-json-schema#124]
Any app should be secure by default, Forget to make a field optional is not a security bug, but forget to make a field required is a security bug.

Any comments?

**Comment by mcollina** [comment]
This library aims to be a low-friction way to create JSON schema documents. In JSON schema, you have to mark a property as required and not vice versa. I think this would be too much of a breaking change from the spec.

If you would like to change that, I'd recommend you to bring this discussion to the committee designing JSON schema.

**Comment by erfanium** [comment]
That change does not seem to be possible on JSON schema design, Mainly because it's too breaking.
But I still think this change can be applied in `fluent-json-schema`. Maybe it would be better to talk more about this. And feel free to close this issue. I have nothing new to add
Thanks!

**Comment by mcollina** [comment]
Thanks for the interesting discussion.
