### ISSUE TITLE
.id and .required not returning schema object

### ISSUE THREAD

**Issue by maxvanceffer** [fastify/fluent-json-schema#128]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

^3.4.1

### Node.js version

14

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Big Sur 11.3.1

### Description

While building schema and calling .id or .required, and after that trying to add some props, rises error:

TypeError: Schema.id(...).object is not a function

### Steps to Reproduce

const Schema = require('fluent-json-schema')

Schema
  .id('my-example-id')
  .object()

Rise next error:
 TypeError: Schema.id(...).object is not a function

The same error appears when trying to add some props after colling .required

### Expected Behavior

Ability to make chain like this:

Schema.id('some-id').required(['param1', 'param2']).props('name', Schema.string())

**Comment by aboutlo** [comment]
the syntax is wrong, have a look here: https://github.com/fastify/fluent-json-schema#usage

it  should be:

```
Schema.object().id('my-example-id')

```
