### ISSUE TITLE
.raw({ nullable: true }) being inserted in the wrong position

### ISSUE THREAD

**Issue by denisdifazio** [fastify/fluent-json-schema#129]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.6

### Node.js version

12

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

20H2

### Description

fluent-json-schema version: `3.0.0`

When using .`raw({ nullable: true })` with a type object schema, the generated schema is wrong.

### Steps to Reproduce

I created the following unit test to reproduce the bug:

```
import S from 'fluent-json-schema';

describe('parent', () => {
  expect(
    S.object()
      .required(['symbol', 'productType'])
      .prop('symbol', S.string())
      .prop('productType', S.string())
      .raw({ nulllable: true })
      .valueOf(),
  ).toEqual({
    $schema: 'http://json-schema.org/draft-07/schema#',
    type: 'object',
    nullable: true,
    required: ['symbol', 'productType'],
    properties: {
      symbol: {
        type: 'string',
      },
      productType: {
        type: 'string',
      },
    },
  });
});
```

### Expected Behavior

Expected output:

```
{
    $schema: 'http://json-schema.org/draft-07/schema#',
    type: 'object',
    nullable: true,
    required: ['symbol', 'productType'],
    properties: {
      symbol: {
        type: 'string',
      },
      productType: {
        type: 'string',
      },
    },
}
```

Received:

```
{
    $schema: 'http://json-schema.org/draft-07/schema#',
    type: 'object',
    required: ['symbol', 'productType'],
    properties: {
      symbol: {
        type: 'string',
      },
      productType: {
        nullable: true, // nullable is being inserted here
        type: 'string',
      },
    },
}
```

**Comment by aboutlo** [comment]
This is happening because of the way you declare the schema:

```
S.object()
      .required(['symbol', 'productType'])
      .prop('symbol', S.string())
      .prop('productType', S.string())
      .raw({ nulllable: true })
```

the  `.raw({ nulllable: true })` is attached to the last entity. In this case `productType` property.

try this instead: 

```
S.object()
      .raw({ nulllable: true })
      .required(['symbol', 'productType'])
      .prop('symbol', S.string())
      .prop('productType', S.string())
```

I prefer to keep everything inside the property so it's "atomic"

```
S.object()
      .raw({ nulllable: true })
      .prop('symbol', S.string().required())
      .prop('productType', S.string().required())
```

**Comment by denisdifazio** [comment]
Thanks for the tips @aboutlo !

But when I try the way you described I got an error `Property 'required' does not exist on type 'JSONSchema'.` on the `.required()` line as shown below:

![image](https://user-images.githubusercontent.com/11673757/119174024-7181c200-ba3e-11eb-8044-0b35e86653a8.png)

**Comment by aboutlo** [comment]
hey, @denisdifazio this is an issue with the Typescript types. 
Both the suggestions works: https://runkit.com/embed/yssc1vta8xfc


so if you want to fix you can open a PR and change this file: 
https://github.com/fastify/fluent-json-schema/blob/master/src/FluentJSONSchema.d.ts

**Comment by joaopedrocampos** [comment]
@aboutlo hey, if still up to, I would love to take this fix. Just a question, never did any changes on Typescript types, so it's needed to add a schema on the `index.ts` file to guarantee that this is covered? (Maybe a schema like the one of this issue, just with more generic fields)

**Comment by aboutlo** [comment]
nice! yes, it's still an open issue. 
Correct you have to use a `.raw` in the index.ts to check it compiles correctly. Not sure it worth adding a new schema perhaps just add the property but if it's easier to check multiple scenarios it's o.k

**Comment by joaopedrocampos** [comment]
Hey @aboutlo! Do you think this issue should be closed now? I tried to assign it on the PR to close it automatically on the PR  merge, but did not had permission to do it
