### ISSUE TITLE
Root level `required` creates invalid schema

### ISSUE THREAD

**Issue by erfanium** [fastify/fluent-json-schema#132]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.0.0

### Plugin version

3.0.0

### Node.js version

16.2.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

18.04

### Description

I think root level required calls should be ignored, because it creates an invalid schema

### Steps to Reproduce

```js
const s = S.object().required().prop('foo', S.string())
ajv.compile(s.valueOf())
```

Result:
```
Error: schema is invalid: data/required/0 must be string
```

Because `s.valueOf().required` array contains a `symbol` but it expected to be an array of string

### Expected Behavior

`S.object().required().prop('foo', S.string()).valueOf()` should return a valid json-schema

**Comment by erfanium** [comment]
One possible solution is to separate internal-use and external-use of `valueOf` method by creating a new method like `_valueOf` for internal use.

I can make a PR with this solution

**Comment by aboutlo** [comment]
hey, @erfanium thank you for raising this. Not sure about the solution, to me is a misusage of the DSL.  In the end, the AJV compiler will raise the problem. I'm not a big fan of splitting the implementations from internal and external usage. 
Perhaps we could just throw an exception if `required()` is invoked at the root level.

**Comment by mcollina** [comment]
> hey, @erfanium thank you for raising this. Not sure about the solution, to me is a misusage of the DSL. In the end, the AJV compiler will raise the problem. I'm not a big fan of splitting the implementations from internal and external usage.
> Perhaps we could just throw an exception if `required()` is invoked at the root level.

I think that'd be a good idea!

**Comment by erfanium** [comment]
> Perhaps we could just throw an exception if `required()` is invoked at the root level.

How to detect root level `required()`?

**Comment by mcollina** [comment]
You can only detect it when `.valueOf()` is called.

**Comment by aboutlo** [comment]
Good question, the problem is that we could have:
```
const leaf = S.object().required()  // rootLevel shouldn't throw
S.object().required().prop('leaf', leaf) // rootLevel should throw
```

Even adding a flag `root:true` here https://github.com/fastify/fluent-json-schema/blob/master/src/BaseSchema.js#L17 doesn't help that much because we resolve each schema independently

so it seems we can't do it when we invoke `required()` but only later via `valueOf`

**Comment by erfanium** [comment]
> but only later via valueOf

Also `valueOf` has some internal usage. it will call multiple times per schema

**Comment by mcollina** [comment]
You can detect you are "within" a parent `valueOf` via an option param, or using a private method `_valueOf` for the recursion.
