### ISSUE TITLE
Support "dependentrequired" and "dependentSchemas"

### ISSUE THREAD

**Issue by StarpTech** [fastify/fluent-json-schema#135]
## 🚀 Feature Proposal

As titled. The keywords are part of draft-7 https://json-schema.org/draft/2019-09/release-notes.html

## Motivation

"dependencies" keyword has been deprecated.

## Example

- https://ajv.js.org/json-schema.html#dependentschemas
- https://ajv.js.org/json-schema.html#dependentrequired

**Comment by mcollina** [comment]
This would be nice to have

**Comment by joaopedrocampos** [comment]
Hey! If possible I would love to do this feature 🙏

**Comment by aboutlo** [comment]
go for it @joaopedrocampos!

**Comment by joaopedrocampos** [comment]
Hey @aboutlo! Do you think this issue should be closed now? I tried to assign it on the PR to close it automatically on the PR  merge, but did not had permission to do it

**Comment by StarpTech** [comment]
@joaopedrocampos thanks! I'll close it.
