### ISSUE TITLE
100 % code coverage

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fluent-json-schema#188]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

It would be good to have 100% test coverage. 

If we merge https://github.com/fastify/fluent-json-schema/pull/178 then we have only one branch left to cover. 

https://github.com/fastify/fluent-json-schema/blob/b9c32d08af0de9e81254660a6d9e039e6f37fa34/src/utils.js#L124 

I think it is not even possible, that definition becomes truthy.

**Comment by aboutlo** [comment]
@Uzlopak we did merge #178 :) 

I wrote that line a few years ago intentionally, but I can't remember the actual reason :) You could be right; the simplest would be to try to remove it and see if we got any red tests. Perhaps, it was driven by a wrong assumption
