### ISSUE TITLE
validate GET array of array param

### ISSUE THREAD

**Issue by stefanocudini** [fastify/fluent-json-schema#206]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I have an endpoint in this format:

fastify route path:
```javscript
  fastify.get('/bbox/:locations', {
    schema: {
      description: 'Get locations stringified',
      params: S.object()
        .prop('locations', S.string()).required()
    }
  }, async req => {
  const locations = req.params.locations.split('|').map(a=>a.split(',').map(Number));
  ...
  })
```
request example:
`GET /bbox/11.1,46.1|11.2,46.2|11.3,46.3`

This is a common way to accept comma separated lists of locations in GET requests.
How can i validate more strictly way the format of _locations_ with comma required?

**Comment by climba03003** [comment]
Use [`pattern`](https://json-schema.org/understanding-json-schema/reference/string.html#regular-expressions) for validating the string

**Comment by stefanocudini** [comment]
partial of solution here:
https://gist.github.com/stefanocudini/d8d95133551ea4158e3bc5b8a6a77075#file-valid-locations-js-L6-L16
