### ISSUE TITLE
Crashes on import

### ISSUE THREAD

**Issue by ghost** [fastify/fluent-json-schema#212]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

0.0.0

### Plugin version

4.1.0

### Node.js version

v12.22.9

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

linux

### Description

import crashes 

`import S from 'fluent-json-schema'`

Does it need any peer dependencies ?

I'm having:

> /home/aben/schema/node_modules/@fastify/deepmerge/index.js:72
>   const cloneProtoObject = typeof options?.cloneProtoObject === 'function'
>                                           ^
> 
> SyntaxError: Unexpected token '.'
>     at wrapSafe (internal/modules/cjs/loader.js:915:16)
>     at Module._compile (internal/modules/cjs/loader.js:963:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>     at Module.load (internal/modules/cjs/loader.js:863:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
>     at Module.require (internal/modules/cjs/loader.js:887:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (/home/aben/schema/node_modules/fluent-json-schema/src/utils.js:2:19)
>     at Module._compile (internal/modules/cjs/loader.js:999:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

### Steps to Reproduce

Just import with the exact versions.

**Comment by Uzlopak** [comment]
Node 12 does not support optional chaining.
