### ISSUE TITLE
Nullable false not working

### ISSUE THREAD

**Issue by conduongtong** [fastify/fluent-json-schema#215]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.9.2

### Plugin version

4.1.0

### Node.js version

18.5.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

I tried to not allow null in string but it's not working:
How can I not allow null, even string array like this: [null]

### Steps to Reproduce

Code that I tested not working
```js
S.string()
S.string().raw({nullable: true})
S.string().not(S.null())
```
Workaround: 
```js
S.ifThenElse(S.null(), S.not(S.null()), S.string())
```

**Comment by Eomm** [comment]
Could you add a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

Without it, we are unable to help you.

This module generates json schema, so that code generates:

```
{$schema: "http://json-schema.org/draft-07/schema#", type: "string", nullable: true}
```

https://runkit.com/embed/wdwudrwu14aa
