### ISSUE TITLE
Migrate test suite from `jest` to `node:test`

### ISSUE THREAD

**Issue by gurgunday** [fastify/fluent-json-schema#243]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

**Comment by aboutlo** [comment]
I would prefer `node:test` :)

**Comment by gurgunday** [comment]
Agreed ;)

And for more information: we recently moved from jest to `node:test` in fastify-awilix: https://github.com/fastify/fastify-awilix/pull/134

**Comment by kibertoad** [comment]
Let's mention node:test explicitly in the description, so that we are consistent across fastify ecosystem

**Comment by Fdawgs** [comment]
Closed by #245
