### ISSUE TITLE
Coverage badge broken

### ISSUE THREAD

**Issue by aboutlo** [fastify/fluent-json-schema#28]
https://coveralls.io/github/fastify/fluent-schema?branch=master doesn't return the coverage. 
@mcollina it seems to me this is related to how fastify is handled by coveralls.io but I'm not sure

**Comment by mcollina** [comment]
I can't really add/configure this. coveralls is totally broken for me as I have too many repos.

**Comment by aboutlo** [comment]
http://docs.coveralls.io/troubleshooting

>I can’t add repos from an organization of which I’m a member.
>
>If your membership of an organization is not publicized (your username isn’t listed on the >organization’s Github page), Coveralls can’t see it either, so you’ll need to upgrade your OAuth scope >to private here:
> https://coveralls.io/refresh?private=true

it could be that the case?  or someone else from fastify can help on that. No rush I think it's nice to have
