### ISSUE TITLE
Node 6 support

### ISSUE THREAD

**Issue by Eomm** [fastify/fluent-json-schema#29]
Hi,
adding some test to verify the usage of fluent-schema with fastify, I found fluent-schema doesn't work with node.js 6.x. Since it is supported by fastify v2, it would be great to support it too.

Here https://github.com/fastify/fastify/pull/1485#issuecomment-467588781 more details with CI failure.

I test it also locally and I get the same behaviour with node.js 6 and 7:

![image](https://user-images.githubusercontent.com/11404065/53442440-9165df00-3a09-11e9-9082-eaf996b0bdaf.png)

With node.js >= 8 all is fine.

I'm not a TypeScript dev, but if you would like to give me some information I would be glad to help if it is needed.

**Comment by aboutlo** [comment]
You are right fluent-schema doesn't work with node 6.  
The node 6 LTS end-of-life is 2019-04-01 because of that I decided to not support node 6
https://nodejs.org/en/about/releases/

**Comment by Eomm** [comment]
Ok, and it is also written but I didn't check the engine prop also:
https://github.com/fastify/fluent-schema/blob/7078f8b74b4e8fb3a29ec1f84ac85c275de96013/package.json#L30

My fault 🙌
