### ISSUE TITLE
Question: how to implement a basic object schema?

### ISSUE THREAD

**Issue by jsumners** [fastify/fluent-json-schema#41]
Basically, I want to implement this test with `fluent-schema` -- https://github.com/fastify/fast-json-stringify/blob/06acd3bf09a6c0136eb442d0d95e2a5b1fd85cf2/test/additionalProperties.test.js#L68-L79

My attempt keeps resulting in various errors -- https://runkit.com/embed/ep1pfme4238t

```js
var fastJson = require('fast-json-stringify')
var fluent = require("fluent-schema")
var schema = fluent.object().prop(
    'error',
    fluent.object().additionalProperties(true).prop('message')
)
console.log(schema.valueOf())
var stringify = fastJson(schema.valueOf())
stringify({ error: { message: 'foo', code: 'internal_server_error' } })
```

**Comment by aboutlo** [comment]
I don't know how it works fastJson in details but I have the feeling the issue could be there

to me
```js
{
    title: 'check string coerce',
    type: 'object',
    properties: {},
    additionalProperties: true
  }
```

become 

```js
const schema = S.object().additionalProperties(true).title('title string coerce')
console.log(JSON.stringify(schema.valueOf(),undefined,2))
```

which will generate
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "additionalProperties": {},
  "title": "title string coerce"
}
```

I wonder about `additionalProperties: true` it isn't required to be set as `true` because by default a schema accepts an object with extra props. `additionalProperties: true` will be translated as additionalProperties: {} 

So either you set to `false` or you pass a schema to specify which kind of extra props you want.

**Comment by jsumners** [comment]
Without `additionalProperties:true` fast-json-stringify will strip properties that are explicitly stated in the schema.

**Comment by aboutlo** [comment]
So looking to the reference: 
https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.5.6

> The value of "additionalProperties" MUST be a valid JSON Schema. 

So the bug is here: https://github.com/fastify/fluent-schema/blob/73adbf43075104d5ac05a874313fd7dbbda72474/src/ObjectSchema.js#L52-L52

we should need something like this:
```js
additionalProperties: value => {
      if (typeof value !== 'boolean' && !isFluentSchema(value))
        throw new Error("'additionalProperties' must be a boolean or a FluentSchema object")
      const attribute =
        typeof value === 'boolean'
          ? value.valueOf()
          : omit(value.valueOf(), ['$schema'])
      return setAttribute({ schema, ...options }, [
        'additionalProperties',
        attribute,
        'array',
      ])
    }
```

**Comment by jsumners** [comment]
FYI: re-reading this issue this morning I noticed that I left out a "not" in my last reply. Please re-read it to make sure it still makes sense.

**Comment by aboutlo** [comment]
Still, a bug in fluent because of the spec

given  
```
const schema = S.object().additionalProperties(true).title('title string coerce')
```

expect: 

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "additionalProperties": true,
  "title": "title string coerce"
}
```


rather than:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "additionalProperties": {},
  "title": "title string coerce"
}
```

However, `additionalProperties: {}` is valid it means don't strip 
I found somewhere else where they are discussing the same topic: https://github.com/OAI/OpenAPI-Specification/issues/668#issuecomment-280377470

**Comment by aboutlo** [comment]
PR merged
