### ISSUE TITLE
Using custom keywords?

### ISSUE THREAD

**Issue by firasdib** [fastify/fluent-json-schema#51]
AJV has support to add custom keywords, but I don't see any way of using these with fluent schema.

AJV will accept this:

```
{
  foo: {
    type: 'integer'
  },
  myKeyword: true,
}
```

but I have no idea how to do something like this in fluent-schema, if its even possible.

**Comment by aboutlo** [comment]
fluent-schema doesn't support custom AJV keywords.  we had a similar discussion here: https://github.com/fastify/fluent-schema/issues/16 

To be fair, I'm not sure if it's a good idea to add not standard keywords related to a specific validator (e.g. AJV). 

Regardless can you give an example of API that would you like to use

**Comment by firasdib** [comment]
@aboutlo Okay. I wanted to add a specific type/keyword to be able to manipulate the data to my needs in a generic way.

**Comment by aboutlo** [comment]
maybe we could think something like that. 

```
S.object()
  .prop('foo', S.integer())
  .prop('myKeyword', S.raw({true})
```


//cc @mcollina @Eomm

**Comment by Eomm** [comment]
Is `S.raw` a type or could be attached like prop?
```
S.object()
  .prop('foo', S.integer())
  .prop('myKeyword', S.raw('true')
  .raw({$def:S.object().valueOf()})
```

And the input could be:
- a json => an will be that will be spread
- a string/bool/num => and will be used as value
?

**Comment by aboutlo** [comment]
I imagined as a type in order to accept an arbitrary valid JSON. 
In your example I don't get the benefit. it could be `S.definition(S.raw({ foo: 'bar'}))`

**Comment by firasdib** [comment]
Unless I've missed something, adding support for this would allow us to use the `nullable` feature in AJV/OpenAPI, which I currently don't think is possible with fluent schema.

**Comment by aboutlo** [comment]
Yes, any feature outside JSON Schema spec isn't currently supported

**Comment by aboutlo** [comment]
Moved the conversation here: https://github.com/fastify/fluent-schema/issues/55
