### ISSUE TITLE
sugar feature: string length

### ISSUE THREAD

**Issue by Eomm** [fastify/fluent-json-schema#53]
## 🚀 Feature Proposal

Add a `.length(24)` method as a shortcut for min + max length.

## Motivation

Right now to add a check for a string I need to write:

```
S.string().minLength(24).maxLength(24)
```

## Example

```
S.string().length(24)
```

WDYT?

**Comment by aboutlo** [comment]
I like the idea of having shortcuts. However, diverging from the JSON Schema API could bring issues in the future. 
What if `length` would be added in the spec with a different meaning?
As well the saving or the productivity boost isn't that much. 
 
Maybe you could have a shortcut definition for your usecase
```js
const sLenght = (length) => S.string().minLength(length).maxLength(length)
S.object().prop('foo', sLenght(24))
```
