### ISSUE TITLE
Confusing documentation about `required`

### ISSUE THREAD

**Issue by chengluyu** [fastify/fluent-json-schema#57]
None of the issue template is about documentation, so I opened a blank issue.

In fastify docs (https://github.com/fastify/fastify/blame/master/docs/Fluent-Schema.md#L79), `required` is called after `prop` was called (e.g. `S.object().prop('x', S.string()).required()`). 

In fluent-schema's docs, `required` is called either inside of `prop` (e.g. `S.object().prop('x', S.string().required())`) or outside but with arguments (e.g. `S.object().prop('x', S.string()).required(['x'])`).

So far, we have 3 different usage of `required`. All of them works on the lastest fluent-schema (see REPL results below). I think docs should illustrate all possible usage of a function. How could we improve?

```
> S.object().prop('y', S.string()).prop('x', S.string()).required().valueOf()
{
  '$schema': 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  properties: { y: { type: 'string' }, x: { type: 'string' } },
  required: [ 'x' ]
}
> S.object().prop('y', S.string()).prop('x', S.string().required()).valueOf()
{
  '$schema': 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  properties: { y: { type: 'string' }, x: { type: 'string' } },
  required: [ 'x' ]
}
> S.object().prop('y', S.string()).prop('x', S.string()).required(['x']).valueOf()
{
  '$schema': 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  properties: { y: { type: 'string' }, x: { type: 'string' } },
  required: [ 'x' ]
}
```

**Comment by aboutlo** [comment]
The idea is to let the user pick what approach they prefer. 

Currently, the doc of `required` can be found here:  https://github.com/fastify/fluent-schema/blob/master/docs/API.md#required

If something is missing, please open a PR to improve the js doc. 

Generally speaking, I'm not happy with the documentation template.  Any help on this topic would be appreciated.

**Comment by chengluyu** [comment]
> The idea is to let the users picking what approach they prefer.
> 
> Currently, the doc of `required` can be found here: [/docs/API.md@`master`#required](https://github.com/fastify/fluent-schema/blob/master/docs/API.md#required) [](/fastify/fluent-schema/blob/HEAD@{2020-01-11T14:15:18Z}/docs/API.md#required)
> 
> If something is missing, please open a PR to improve the js doc.
> 
> Generally speaking, I'm not happy with the documentation template. Any help on this topic would be appreciated.

Sorry! I didn't read README thoroughly. But IMHO the link [here](https://github.com/fastify/fluent-schema#documentation) is somewhat inconspicuous. Also, I found a typo in the doc. Here is the PR: #58 .

**Comment by aboutlo** [comment]
thank you @chengluyu !
