### ISSUE TITLE
Hack workaround for multiple-extend

### ISSUE THREAD

**Issue by dfee** [fastify/fluent-json-schema#75]
## 🐛 Bug Report

multiple extend was broken here: https://github.com/fastify/fluent-schema/pull/69
it was sort of fixed here: https://github.com/fastify/fluent-schema/pull/74

however, the result is the hack function below to extend multiple times:
```ts
export const extendMultiple = (...schemas: ObjectSchema[]): ObjectSchema =>
  schemas.reduce((prev, curr) => curr.extend(prev), S.object());
```

## To Reproduce
```ts
// extend is not a function (technically, the second extend doesn't exist)
S.object().extend(S.object()).extend(S.object())
```

```ts
// ...or
const schema = extendMultiple(S.object(), S.object(), S.object());
```

## Expected behavior

`extend` shouldn't be excluded from the return value here: https://github.com/fastify/fluent-schema/blob/5ffffb8110a6fe845ca6cd7bbaaf2dc358960b5a/src/ObjectSchema.js#L261-L278

## Your Environment

- *node version*: 12
- *os*: Mac,
- *fluent-schema version*: 1.0.3

**Comment by dfee** [comment]
Also, it's unclear what this means:

>  I decided to block all the method after .extend to avoid incorrect usage.

from https://github.com/fastify/fluent-schema/pull/69#issue-415436305

What is the incorrect usage?

**Comment by aboutlo** [comment]
```js
const base = S.object()
  .extend(SCHEMA_BASE)
  .prop(
    'reason',
    S.string()
      .minLength(1)
  )
```
the fact that you first `extend` then you add the `prop` it could easily create confusion. 

On the other hand, this is a fair case
```
S.object().extend(S.object()).extend(S.object())
```

**Comment by dfee** [comment]
Looks good! Any plan on merge / release?

**Comment by aboutlo** [comment]
v1.0.4 has been. published
