### ISSUE TITLE
How to verify the file upload field?

### ISSUE THREAD

**Issue by caryhgq** [fastify/fluent-json-schema#77]
## Current Problem
```js
const upLoadBodySchema = S.object()
  .prop('fileName', S.string())
  .prop('file', S.required().raw({ type: 'string', format: 'binary'}));  // There's going to be an error
```
```bash
Service Startup Failed! FastifyError [Error]: Failed building the validation schema for POST: /upload, due to error unknown format "binary" is used in schema at path "#/properties/file"
    at Boot.<anonymous> (F:\node-server-fastify\node_modules\fastify\lib\route.js:261:19)
    at Object.onceWrapper (events.js:421:28)
    at Boot.emit (events.js:327:22)
    at F:\node-server-fastify\node_modules\avvio\boot.js:153:12
    at F:\node-server-fastify\node_modules\avvio\plugin.js:269:7
    at done (F:\node-server-fastify\node_modules\avvio\plugin.js:201:5)
    at check (F:\node-server-fastify\node_modules\avvio\plugin.js:225:9)
    at internal/process/task_queues.js:153:7
    at AsyncResource.runInAsyncScope (async_hooks.js:186:9)
    at AsyncResource.runMicrotask (internal/process/task_queues.js:150:8) {
  code: 'FST_ERR_SCH_VALIDATION_BUILD',
  statusCode: 500
}
```

## Expected behavior
How should I correctly verify the uploaded file?

Refer to the Swagger documentation for the above
https://swagger.io/docs/specification/describing-request-body/file-upload/?sbsearch=file
## Environment

- *node version*: v12.18.0
- *fastify version*: >=3.1.1
- *os*:  Windows
- *fluent-schema version*: >=1.0.4

**Comment by aboutlo** [comment]
Please add  the output of the schema from  `upLoadBodySchema. valueOf()`

**Comment by caryhgq** [comment]
@aboutlo 
{
  '$schema': 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  properties: {
    fileName: { type: 'string'},
    file: { type: 'string' }
  },
  required: [ 'file' ]
}

**Comment by aboutlo** [comment]
but the `format: "binary"` is missing despite fastify is throwing an error about it 🤔 

I double-checked the actual output is:
```
{
   "$schema":"http://json-schema.org/draft-07/schema#",
   "type":"object",
   "properties":{
      "fileName":{
         "type":"string"
      },
      "file":{
         "type":"string",
         "format":"binary"
      }
   },
   "required":[
      "file"
   ]
}
```

which is correct. So the issue isn't in `fluent-schema`
I found this here: https://github.com/fastify/fastify-swagger/issues/47 
perhaps it can help you to figure out the problem.

**Comment by caryhgq** [comment]
Thank you very much
