### ISSUE TITLE
Get "some" properties from schema (easier than ref/id)

### ISSUE THREAD

**Issue by jillesme** [fastify/fluent-json-schema#84]
## 🚀 Feature Proposal

v0.1 - just an idea, hoping to get some feedback. 

Get Fluent Schema properties from another Fluent Schema to re-use in other schemas. This way you could build schemas easily from existing schemas.

I realize that with `extend` and `$id, $ref`, this is possible. However, I ended up with a `schema.js` file which had a lot of properties defined which I would then use all over the place. It would be nice to have one larger / more complex schema as "the source of truth" and be able to create sub schemas from it.

## Motivation

I've created a fairly complex JsonSchema object using `fluent-schema`. Now I'd like to create some smaller schemas from it. One of the ways is described here https://www.fastify.io/docs/latest/Fluent-Schema/#reuse using ref/id. While this is the official JsonSchema way of doing so, I thought it could be simpler.

## Example

```js
// Create very long schema
const userSchema =  S.object()
  .prop('id', S.integer().readOnly())
  .prop('username', S.string().minLength(3).maxLength(48))
  .prop('password', S.string().minLength(8).maxLength(255))
  .prop(...);

// Now use some of those props somewhere else
const otherSchema = userSchema.only(['username', 'password'])
```

Additionally, instead of https://github.com/fastify/fluent-schema#extend-schema, one could do

```js
const userSchema = S.object()
  .prop('id', S.string().format('uuid'))
  .prop('username', S.string())
  .prop('password', S.string())
  .prop('createdAt', S.string().format('time'))
  .prop('updatedAt', S.string().format('time'));

const userSchemaForPost = userSchema.only(['username', 'password']);
```

**Comment by mcollina** [comment]
This is really nice!

**Comment by jillesme** [comment]
Merged, thanks y'all!
