### ISSUE TITLE
ObjectSchema.required without parameters wrongly set the last prop as required

### ISSUE THREAD

**Issue by thezzisu** [fastify/fluent-json-schema#86]
## 🐛 Bug Report

`ObjectSchema.required()` should add itself as a required property to its parent.
However, calling it will wrongly make the last prop defined as required

## To Reproduce

```js
console.log(
    S.object()
      .prop(
        'perm',
        S.object()
          .prop('admin', S.boolean())
          .prop('comment', S.boolean())
          .required()
      )
      .valueOf()
  )
```

will output:
```js
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "perm": {
      "type": "object",
      "properties": {
        "admin": {
          "type": "boolean"
        },
        "comment": {
          "type": "boolean"
        }
      },
      "required": [
        "comment"
      ]
    }
  }
}
```

## Expected behavior
```js
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "perm": {
      "type": "object",
      "properties": {
        "admin": {
          "type": "boolean"
        },
        "comment": {
          "type": "boolean"
        }
      }
    }
  },
  "required": [
    "perm"
  ]
}
```

## Your Environment

- *node version*: 14
- *fastify version*: >=2.0.0
- *os*: Windows

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by zzisu** [comment]
I've seen this in fluent-schema's code:
https://github.com/fastify/fluent-schema/blob/b5a5c80334529a2febcc4b3a54b35f5680752e3a/src/BaseSchema.js#L180
```js
/**
   * Required has to be chained to a property:
   * Examples:
   * - S.prop('prop').required()
   * - S.prop('prop', S.number()).required()
   * - S.required(['foo', 'bar'])
```
But in the README.md it's used like this:
```js
.prop(
    'email',
    S.string()
      .format(S.FORMATS.EMAIL)
      .required() // <- It's not chained to `prop` call !
  )
```

I'm wondering which one is correct?

**Comment by aboutlo** [comment]
The correct schema is:
```js
    S.object()
      .prop(
        'perm',
        S.object()
          .required()
          .prop('admin', S.boolean())
          .prop('comment', S.boolean())
      )
      .valueOf()
```

If you put `required()` after a property definition it's attached to the last property declared ( `comment` in this case )

The README is correct because in the case of the `String.format('EMAIL').required()` there isn't a property so we attach `required` to the root element. 

Given that I agree the README is a bit misleading perhaps we could put `String.required().format('EMAIL')` to be more consistent. Also, we could add in the main example a required object so we can show the correct syntax.

**Comment by zzisu** [comment]
Thanks very much! I'll close this issue now.
