### ISSUE TITLE
Rename fluent-schema to fluent-json-schema

### ISSUE THREAD

**Issue by aboutlo** [fastify/fluent-json-schema#87]
##. Rename fluent-schema to fluent-json-schema

Rename `fluent-schema` to `fluent-json-schema`

## Motivation

To foster discoverability of the package via npmjs.com and search engines in general. I believe it would help to have JSON directly in the name aka `fluent-json-schema`

## Example

`npm install fluent-json-schema`

**Comment by mcollina** [comment]
Can you send a PR to update fastify as well? We use this in tests and docs.

**Comment by mcollina** [comment]
You'd also need to deprecate the previous package.

**Comment by aboutlo** [comment]
@mcollina I deprecated the previous packages. 
Can you rename the current repo name to `fluent-json-schema`? 🙏

**Comment by mcollina** [comment]
done

**Comment by mcollina** [comment]
there seem to be a reference to fluid-schema somewhere.

**Comment by aboutlo** [comment]
@mcollina I fixed a couple of them. One bad typescript wise https://github.com/fastify/fluent-json-schema/pull/89.  Do you see anything else missing?
